### ISSUE TITLE
Error with bare minimum layout: RenderBox was not laid out

### ISSUE THREAD

**Issue by mochar** [mcrovero/rubber#18]
**Describe the bug**
Implementing the bare minimum rubber bottomsheet in my page results in an exception. The exception does not terminate the bottomsheet though, it still works.

**To Reproduce**
Code:

```
class BrowserPage extends StatefulWidget {
  @override
  _BrowserPageState createState() => _BrowserPageState();
}

class _BrowserPageState extends State<BrowserPage> with SingleTickerProviderStateMixin {
  RubberAnimationController _controller;

  @override
  void initState() {
    _controller = RubberAnimationController(
      vsync: this,
      duration: Duration(milliseconds: 200)
    );
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
  return Scaffold(
      // drawer: AppDrawer(),
      // endDrawer: DebugDrawer(),
      body: Container(
        child: RubberBottomSheet(
          lowerLayer: Container(
            color: Colors.blueAccent
          ),
          upperLayer: Container(
            color: Colors.redAccent
          ),
          animationController: _controller,
        ),
      )
    );
  }
}
```

And error:

```
I/flutter (19728): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (19728): The following assertion was thrown during a scheduler callback:
I/flutter (19728): RenderBox was not laid out: RenderStack#abea0 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (19728): 'package:flutter/src/rendering/box.dart': Failed assertion: line 1482 pos 12: 'hasSize'
I/flutter (19728): 
I/flutter (19728): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (19728): more information in this error message to help you determine and fix the underlying cause.
I/flutter (19728): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (19728):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (19728):
I/flutter (19728): When the exception was thrown, this was the stack:
I/flutter (19728): #2      RenderBox.size 
package:flutter/…/rendering/box.dart:1482
I/flutter (19728): #3      _RubberBottomSheetState._bottomSheetHeight 
package:rubber/src/bottom_sheet.dart:50
I/flutter (19728): #4      _RubberBottomSheetState.afterFirstLayout 
package:rubber/src/bottom_sheet.dart:296
I/flutter (19728): #5      __RubberBottomSheetState&State&TickerProviderStateMixin&AfterLayoutMixin.initState.<anonymous closure> 
package:after_layout/after_layout.dart:10
I/flutter (19728): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback
I/flutter (19728): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:936
I/flutter (19728): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame 
package:flutter/…/scheduler/binding.dart:840
I/flutter (19728): #12     _invoke (dart:ui/hooks.dart:209:10)
I/flutter (19728): #13     _drawFrame (dart:ui/hooks.dart:168:3)
I/flutter (19728): (elided 5 frames from class _AssertionError and package dart:async)

```
**Smartphone (please complete the following information):**
 - Device: samsung galaxy s7
 - OS: not sure
 - Browser ??
 - Version Latest flutter and rubber

**Extra:**
As an aside, setting the lowerBoundValue to AnimationControllerValue(pixel: whatever) terminates the upperlayer, i.e. it doesnt show up at all. No error messages except for the one mentioned here.

**Comment by mochar** [comment]
Hate to be a bother but can I perhaps get your thoughts on this?

**Comment by mcrovero** [comment]
With the latest update I'm not seeing the error anymore. 
Please let me know if we can close this
