### ISSUE TITLE
AnimationController.dispose() called more than once

### ISSUE THREAD

**Issue by emaddoma** [mcrovero/rubber#67]
**Describe the bug**

Just using the plugin.  Here is the widget in context within my app and the error produced whenever build is called.

```
return AppScaffold(
          title: 'Book Appointment',
          showAppBar: true,
          showMenu: true,
          showBack: true,
          body: ModalProgressHUD(
            inAsyncCall: state is BookPendingState,
            child: AppBackground(
              child: SafeArea(
                bottom: false,
                child: Theme(
                  data: Theme.of(context).copyWith(
                    unselectedWidgetColor: Colors.white,
                    textTheme: Theme.of(context).textTheme.copyWith(
                      bodyText1: TextStyle(color: Colors.black)
                    )
                  ),
                  child: RubberBottomSheet(
                    animationController: _controller,
                    lowerLayer: getLowerLayer(),
                    headerHeight: 60,
                    header: getHeader(),
                    upperLayer: getUpperLayer()
                    ),
                ),
              ),
            ),
          ),
        );

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
AnimationController.dispose() called more than once.
A given RubberAnimationController cannot be disposed more than once.
The following RubberAnimationController object was disposed multiple times:
  RubberAnimationController#6fcbc(⏭ 0.100; paused; DISPOSED)

When the exception was thrown, this was the stack:
#0      RubberAnimationController.dispose.<anonymous closure> (package:rubber/src/animation_controller.dart:509:9)
#1      RubberAnimationController.dispose (package:rubber/src/animation_controller.dart:516:6)
#2      RubberBottomSheetState.dispose (package:rubber/src/bottom_sheet.dart:125:16)
#3      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4721:11)
#4      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2022:13)
#5      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2020:7)
#6      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4549:14)
#7      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2018:13)
#8      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2020:7)
#9      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4549:14)
#10     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2018:13)
#11     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2020:7)
#12     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4549:14)
#13     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2018:13)
#14     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2020:7)
#15     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4549:14)
#16     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2018:13)
#17     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2020:7)
#18     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4549:14)
#19     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2018:13)
#20     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2020:7)
#21     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4549:14)
#22     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2018:13)
#23     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2020:7)
#24     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4549:14)
#25     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2018:13)
#26     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2020:7)
#27     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5961:14)
#28     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2018:13)
#29     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2020:7)
#30     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4549:14)
#31     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2018:13)
#32     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2020:7)
#33     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5961:14)
#34     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2018:13)
#35     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2020:7)
#36     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4549:14)
#37     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2018:13)
#38     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2020:7)
#39     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4549:14)
#40     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2018:13)
#41     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:2020:7)
#42     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6076:16)
#43     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2018:13)
#44     ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#45     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:2031:25)
#46     BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2785:27)
#47     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2585:15)
#48     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2784:7)
#49     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:875:19)
#50     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#51     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#52     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#53     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
#57     _invoke (dart:ui/hooks.dart:161:10)
#58     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:253:5)
#59     _drawFrame (dart:ui/hooks.dart:120:31)
(elided 3 frames from dart:async)
```

Followed by:
```
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: Null check operator used on a null value
#0      RubberAnimationController.stop (package:rubber/src/animation_controller.dart:500:12)
#1      RubberAnimationController._animateToInternal (package:rubber/src/animation_controller.dart:417:5)
#2      RubberAnimationController.animateTo (package:rubber/src/animation_controller.dart:356:12)
#3      RubberAnimationController.expand (package:rubber/src/animation_controller.dart:333:12)
#4      _BookServicesState.build.<anonymous closure>.<anonymous closure> (package:ellabliss/book/services.dart:567:25)
#5      State.setState (package:flutter/src/widgets/framework.dart:1267:30)
#6      _BookServicesState.build.<anonymous closure> (package:ellabliss/book/services.dart:560:11)
#7      _BookServicesState.build.<anonymous closure> (package:ellabliss/book/services.dart:549:17)
#8      _BlocConsumerState.build.<anonymous closure> (package:flutter_bloc/src/bloc_consumer.dart:130:26)
#9      _BlocListenerBaseSta<…>
```

**To Reproduce**
1. Use within stateful widget
2. Update the state

**Expected behavior**
No errors

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 N/A

**Additional context**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3.1 20E241 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2019.2)
[✓] VS Code (version 1.56.1)
[✓] Connected device (2 available)
• No issues found!

**Comment by jurrdb** [comment]
I am experiencing the same issue.
